# Generated by Django 5.2.9 on 2025-12-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_conversation_project'),
        ('projects', '0004_alter_project_last_interacted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project'),
        ),
    ]
