# Generated by Django 5.2.9 on 2025-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_interacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
