# Generated by Django 5.2.9 on 2025-12-30 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_interacted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
