# Generated by Django 5.2.9 on 2025-12-06 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=512)),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("size", models.BigIntegerField(null=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
        ),
    ]
