# Generated by Django 5.2.9 on 2025-12-06 16:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('page', models.IntegerField(blank=True, null=True)),
                ('chunk_index', models.IntegerField(default=0)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('chunk_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ('document', 'page', 'chunk_index'),
                'indexes': [models.Index(fields=['chunk_hash'], name='documents_d_chunk_h_fda033_idx'), models.Index(fields=['document', 'page'], name='documents_d_documen_28a5df_idx')],
            },
        ),
    ]
