# Generated by Django 5.2.9 on 2025-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
