# Generated by Django 5.2.9 on 2025-12-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='pending', max_length=32),
        ),
    ]
